# Number of replicas
replicaCount: 1

# Container image settings
image:
  repository: ghcr.io/nobreak-labs/go-myweb
  tag: latest  # Available: 1.0, 2.0, 3.0, 4.0, alpine, latest
  pullPolicy: IfNotPresent  # Available: Always, IfNotPresent, Never

# Deployment strategy settings
# strategy:
#   type: RollingUpdate  # Available: RollingUpdate, Recreate
#   rollingUpdate:
#     maxUnavailable: 1  # Number or percentage
#     maxSurge: 1        # Number or percentage

# Service settings
service:
  type: ClusterIP  # Available: ClusterIP, NodePort, LoadBalancer
  port: 80
  # nodePort: 30080  # Required for NodePort/LoadBalancer (30000-32767)
