apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
  - name: http
    port: {{ .Values.service.port | default 80 }}
    targetPort: http
    protocol: TCP
    {{- if and (ne .Values.service.type "ClusterIP") .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}